# Some links from the original MS provided scripts (which I couldn't get to work)
# -----
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
#
# The working version below is based on
# -----
# https://github.com/Azure/actions-workflow-samples/blob/master/AppService/php-webapp-on-azure.yml
# 
# Some notes on this script
# -----
# Deployment folder is set at bottom in package


name: Deploy panchotheexplorer to Azure Web App (when master changes)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@master
      - name: 'Deploy to Azure Web App'

        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'panchotheexplorer'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EC222F954DE34D68B09B3AF7AE4C07C8 }}
          package: ./game
